server:
  port: 8088

spring:
  application:
    name: easy-trip


login:
  info:
    clientId: 8835c32278deb2d44aee
    clientSecret: a9de2fca2b4d9cb378d331864631e31286bdd897
    redirectUrl: http://9s5n77.natappfree.cc/api/access/callback
    state: STATE
    scope: user
    accessTokenUrl: https://github.com/login/oauth/access_token
    authorizeUrl: https://github.com/login/oauth/authorize?client_id=%s&redirect_uri=%s&state=%s

---
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
---
spring:
  redis:
    host: 47.103.158.95
    password: steven24
    port: 6379
    timeout: 10000
    #    sentinel:
    #      master: mymaster
    #      nodes: 192.168.43.200:6379,192.168.43.200:6380
    #      password: 123456
    lettuce:
      pool:
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
        max-active: 100